XES_FILES_DIR = './xes_files'
XES_FILES_COMBINED_PATH = './xes_files_combined/combined_log.xml'
XES_FILES_COMBINED_PATH_TEST = './xes_files_combined/combined_log_TEST.xml'  # TODO remove
BLF_JAR_PATH = './blf/blf-cmd.jar'
BLF_VALIDATE = 'validate'
BLF_EXTRACT = 'extract'
TEST_FILES_LOCATION = './test_app/test_files'
TEST_FILES_DESTINATION = "./xes_files"
DIAGRAMS_PATH = 'static/diagrams/'  # Do not add './' to the front.
MANIFEST_PATH = 'static/user_uploads/manifest.bcql'
BPMN_PATH = 'static/user_uploads/diagram.bpmn'
BPMN_EMPTY_PATH = 'static/empty-diagram.bpmn'
ALLOWED_MANIFEST_EXTENSIONS = {'txt', 'bcql'}
ALLOWED_BPMN_EXTENSIONS = {'xml', 'bpmn'}
SETTINGS_PATH = 'static/user_uploads/settings.json'
